[package]
name = "zygisk-rs"
version = "0.1.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
v2 = []
v3 = []
v4 = []
default = ["v2"]

[dependencies]
jni = "0.21.1"
libc = "0.2"
